/**
 * Copyright (c) 2012 ooxi/gltoolkit
 *     https://github.com/ooxi/gltoolkit
 *
 * This software is provided 'as-is', without any express or implied warranty.
 * In no event will the authors be held liable for any damages arising from the
 * use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 *  1. The origin of this software must not be misrepresented; you must not
 *     claim that you wrote the original software. If you use this software in a
 *     product, an acknowledgment in the product documentation would be
 *     appreciated but is not required.
 * 
 *  2. Altered source versions must be plainly marked as such, and must not be
 *     misrepresented as being the original software.
 *
 *  3. This notice may not be removed or altered from any source distribution.
 */
#include <stdio.h>
#include <stdlib.h>

#include "gltoolkit.h"





/**
 * @return Opened file inside a directory or 0, iff file cannot be opened
 */
static FILE* open_in_directory(uint8_t* directory, uint8_t* file, uint8_t* mode) {
	uint8_t const* separator = "/";

	size_t path_length = strlen(directory) + strlen(separator) + strlen(file) + 1;
	uint8_t* path = alloca(path_length * sizeof(uint8_t));

	snprintf(path, path_length, "%s%s%s", directory, separator, file);
	path[path_length - 1] = 0;

	return fopen(path, mode);
}





/**
 * GetLocalization.com Toolkit
 * ===========================
 *
 * Downloads translations from GetLocalization.com and converts them into
 * gettext sources
 *
 * @param argv[1] GetLocalization.com project name
 * @param argv[2] Working directory
 *
 * Currently this toolkit does several actions at once and is optimized for the
 * Violetland project. A future version might be better generalized and runtime
 * configurable:
 *
 *  0. Validate arguments
 *  1. Fetch all available languages and write them to LINGUAS
 *  2. For every language do
 *     a. Fetch all translations
 *     b. Write po translation file
 */
int main(int argc, char** argv) {

	/* 0. Validate arguments
	 */
	if (3 != argc) {
		fprintf(stderr, "Usage: gltoolkit <project> <working-directory>\n");
		return EXIT_FAILURE;
	}
	uint8_t* program = argv[0];
	uint8_t* project = argv[1];
	uint8_t* working_directory = argv[2];


	/* 1. Fetch all available languages and write them to LINGUAS
	 */
	struct gl_languages* languages = gl_get_languages(project);
	FILE* linguas = open_in_directory(working_directory, "LINGUAS", "wb");

	if (!linguas) {
		fprintf(stderr, "Cannot open %s in %s\n", "LINGUAS", working_directory);
		exit(EXIT_FAILURE);
	}

	size_t i = 0; for (; i < gl_get_languages_count(languages); ++i) {
		struct gl_language* language = gl_get_language(languages, i);
		fprintf(linguas, "%s ", gl_get_language_code(language));
	}
	fclose(linguas);


	/* 2. For every language do
	 */
	i = 0; for (; i < gl_get_languages_count(languages); ++i) {
		struct gl_language* language = gl_get_language(languages, i);
		uint8_t const* language_code = gl_get_language_code(language);
		
		/* 2.a Fetch all translations
		 */
		struct gl_translations* translations = gl_get_translations(
			project, language_code
		);


		/* 2.b Write po translation file
		 */
		size_t po_name_length = strlen(language_code) + strlen(".po") + 1;
		uint8_t* po_name = alloca(po_name_length * sizeof(uint8_t));
		snprintf(po_name, po_name_length, "%s.po", language_code);
		po_name[po_name_length - 1] = 0;

		FILE* po = open_in_directory(working_directory, po_name, "wb");

		/* Check if destination can be written to and output warning
		 */
		if (!po) {
			fprintf(stderr, "Cannot open %s in %s\n", po_name, working_directory);
			exit(EXIT_FAILURE);
		}
		fprintf(po, "# This file was auto generated by %s. DO NOT EDIT\n\n", program);

		/* Write translations
		 */
		size_t j = 0; for (; j < gl_get_translations_count(translations); ++j) {
			struct gl_translation* translation = gl_get_translation(translations, j);

			fprintf(po, "# %s\n", gl_get_translation_context_info(translation));
			fprintf(po, "msgid \"%s\"\n", gl_get_translation_master_string(translation));
			fprintf(po, "msgstr \"%s\"\n", gl_get_translation_string(translation));
			fprintf(po, "\n");
		}


		/* Free translations
		 */
		fclose(po);
		gl_free_translations(translations);
	}


	/* Free resources and exit
	 */
	gl_free_languages(languages);
	return EXIT_SUCCESS;
}


















